/*
 * Purely for local development purposes, as the redirect URI must be HTTPS
 */
var https = require('https');
// var selfSigned = require('openssl-self-signed-certificate');

var app = require('./app');

var httpsPort = process.env.HTTPS_PORT || 443;

var options = {
    key: '-----BEGIN PRIVATE KEY-----\nMIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgFU541r8mEH3QKqcn\nUlo9v13HlJDMw/XUrXAdIVo2t1+hRANCAAS5QC3mooAFQZo9XMTD4FLZyCvhlfkC\npfYaP//lTbrse3NAR3e+yW2orNDa4iasIBjieTRBQdgQLhYAxdpoHq5u\n-----END PRIVATE KEY-----',
    cert: '-----BEGIN CERTIFICATE-----\nMIIEYDCCA0igAwIBAgISBGLRz7FOyVEjfmwDNQbgeueZMA0GCSqGSIb3DQEBCwUA\nMDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD\nEwJSMzAeFw0yMzAzMDkxNjU5MzZaFw0yMzA2MDcxNjU5MzVaMB0xGzAZBgNVBAMT\nEjMtOTYtMTk3LTQ0Lm5pcC5pbzBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABLlA\nLeaigAVBmj1cxMPgUtnIK+GV+QKl9ho//+VNuux7c0BHd77Jbais0NriJqwgGOJ5\nNEFB2BAuFgDF2mgerm6jggJOMIICSjAOBgNVHQ8BAf8EBAMCB4AwHQYDVR0lBBYw\nFAYIKwYBBQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHQYDVR0OBBYEFKTX\nkpoyYxAzEBjPdj0YSvritPJrMB8GA1UdIwQYMBaAFBQusxe3WFbLrlAJQOYfr52L\nFMLGMFUGCCsGAQUFBwEBBEkwRzAhBggrBgEFBQcwAYYVaHR0cDovL3IzLm8ubGVu\nY3Iub3JnMCIGCCsGAQUFBzAChhZodHRwOi8vcjMuaS5sZW5jci5vcmcvMB0GA1Ud\nEQQWMBSCEjMtOTYtMTk3LTQ0Lm5pcC5pbzBMBgNVHSAERTBDMAgGBmeBDAECATA3\nBgsrBgEEAYLfEwEBATAoMCYGCCsGAQUFBwIBFhpodHRwOi8vY3BzLmxldHNlbmNy\neXB0Lm9yZzCCAQUGCisGAQQB1nkCBAIEgfYEgfMA8QB3ALc++yTfnE26dfI5xbpY\n9Gxd/ELPep81xJ4dCYEl7bSZAAABhseHRD4AAAQDAEgwRgIhAKJlX/QTaeDLTuBh\ndJsLn7gNByKY2Cp9djO58kDM+WBiAiEA5PJZ/u/k+lqHO5xl7To2f+IjuexLL4O5\n/kI90gD58dUAdgCt9776fP8QyIudPZwePhhqtGcpXc+xDCTKhYY069yCigAAAYbH\nh0RgAAAEAwBHMEUCIQDxmG22QFJ09FSc7Zna27vsOcssQeBmYzqDqVJHqrt9qAIg\neT/mxKj2fNu1xGf/qsD7vDyNgNiTSK1d1L7gIyMgX+swDQYJKoZIhvcNAQELBQAD\nggEBADNFdyRJvyjy5wzlexs8cifDSQ09Lwo6Zusg02RHpMFXm91tP81yBV6wihb+\n/LZ9RXKGAhQjQfZeXdqt69TrPFJDCO2gXey1YeyrqJpgXUuoY3rxfXzJ8yRmKfCb\nPaQiEKW1001ZxssX6LtBjCWZDYm/R1RmOXUbub2VzqVFkjJcLo38ws4Oi7num0Sg\nDfwkVAqoLUyCfNtsuOfrhPi+CX6+3oJyexZO9gDfDs6Cv1ZHkmQEN1Gst1E/wHU9\n0Tnt6Z2oostk9/R9yYk7JMnPS85Yma4/85fGyzmJTYH7RV/zirlzRTebwn5bJ0Ca\nkswrPYdBMzy+8u9xaM55382g090=\n-----END CERTIFICATE-----'
};

https.createServer(options, app).listen(httpsPort);
console.log(`HTTPS started on port ${httpsPort} (dev only).`);
